#cloud-config
rancher:
  docker:
    registry_mirror: "https://s06nkgus.mirror.aliyuncs.com"
    graph: "/mnt/user-docker"
  system_docker:
    registry_mirror: "https://s06nkgus.mirror.aliyuncs.com"
  environment:
    EXTRA_CMDLINE: /init
  services_include:
    open-vm-tools: true
  state:
    autoformat:
    - /dev/sda
    - /dev/vda
    dev: LABEL=RANCHER_STATE
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6m0rPHFN4POq8f8DFhAcmUtUfzRo2czRHzsIylxHJHFA49fVmJuCXtae0YUAslPE9pTv5iERbYttGsTrDBW+BdNUd2mSeZieqS5Ea/13HXYcq+nhjsrkm/woASjegj58xKxVMentPRai4GpBJJRJ4sMlGh1jfJzmwfP7j0xL0uqV8CKSZm+ljbtKN3RCiJKbjrtZ46V4BQJUkib4e8yC5U4ncz7KG8oXJfFufNNs/SGm+0W4dYN0ANQhy/ARM9OBBsgatJ8p9IwNJ2108uE0NXNROjavTI+tYzHI2zzlgTvIDS8LijYw0gJEX9kxqcpoFSGuY7vsR7oSPm/WdPOZF rancher@wujingdeMacBook-Pro.local

runcmd:
- [ touch, /home/test1 ]
- echo "test" > /home/test1


