hostname: wujing
runcmd:
- echo "test" > /home/rancher/wujing
k3os:
  password: rancher@123
  ssh:
    authorized_keys:
    - ssh-rsa /home/rancher/.ssh/id_rsa
  modules:
  - kvm
  sysctl:
    net.ipv4.conf.default.rp_filter: 1
  network:
    dns:
      nameservers:
      - 8.8.8.8
      - 4.4.4.4
      searches:
      - mydomain.com
      - example.com

