hostname: wujingaa
runcmd:
- echo "test" > /home/rancher/wujingaa
k3os:
  password: rancher@123
  ssh:
    authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6m0rPHFN4POq8f8DFhAcmUtUfzRo2czRHzsIylxHJHFA49fVmJuCXtae0YUAslPE9pTv5iERbYttGsTrDBW+BdNUd2mSeZieqS5Ea/13HXYcq+nhjsrkm/woASjegj58xKxVMentPRai4GpBJJRJ4sMlGh1jfJzmwfP7j0xL0uqV8CKSZm+ljbtKN3RCiJKbjrtZ46V4BQJUkib4e8yC5U4ncz7KG8oXJfFufNNs/SGm+0W4dYN0ANQhy/ARM9OBBsgatJ8p9IwNJ2108uE0NXNROjavTI+tYzHI2zzlgTvIDS8LijYw0gJEX9kxqcpoFSGuY7vsR7oSPm/WdPOZF rancher@wujingdeMacBook-Pro.local
  modules:
  - kvm
  sysctl:
    net.ipv4.conf.default.rp_filter: 1
  network:
#    dns:
#      nameservers:
#      - 8.8.8.8
#      - 4.4.4.4
#      searches:
#      - mydomain.com
#      - example.com
    interfaces:
      enp0s3:
    	addresses:
    	- 192.168.1.103/24
    	gateway: 192.168.1.2
      enp0s8:
    	addresses:
    	- 192.168.1.104/24
    	gateway: 192.168.1.2
