#cloud-config
rancher:
  network:
    interfaces:
      bond0:
        dhcp: true
        bond_opts:
          downdelay: "200"
          lacp_rate: "1"
          miimon: "100"
          mode: "2"
          updelay: "200"
          xmit_hash_policy: layer3+4
      mac=08:00:27*:
        bond: bond0
        dhcp: false
        
