#cloud-config
rancher:
  network:
    interfaces:
      bond0:
        addresses:
        - 192.168.1.110/24
        - 192.168.1.111/24
        - 192.168.1.109/24
        gateway: 192.168.1.1  
        bond_opts:
          downdelay: "200"
          lacp_rate: "1"
          miimon: "100"
          mode: "2"
          updelay: "200"
          xmit_hash_policy: layer3+4
      mac=08:00:27*:
        bond: bond0
        
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6m0rPHFN4POq8f8DFhAcmUtUfzRo2czRHzsIylxHJHFA49fVmJuCXtae0YUAslPE9pTv5iERbYttGsTrDBW+BdNUd2mSeZieqS5Ea/13HXYcq+nhjsrkm/woASjegj58xKxVMentPRai4GpBJJRJ4sMlGh1jfJzmwfP7j0xL0uqV8CKSZm+ljbtKN3RCiJKbjrtZ46V4BQJUkib4e8yC5U4ncz7KG8oXJfFufNNs/SGm+0W4dYN0ANQhy/ARM9OBBsgatJ8p9IwNJ2108uE0NXNROjavTI+tYzHI2zzlgTvIDS8LijYw0gJEX9kxqcpoFSGuY7vsR7oSPm/WdPOZF rancher@wujingdeMacBook-Pro.local
